language: ruby

sudo: false

notifications:
  email: false

rvm:
  - 2.4.0

cache: bundler
bundler_args: --without production deployment

before_script:
  - bin/rails db:test:prepare

# TODO: running `ci` as the default task always runs `spec` first /shrug
script: bundle exec rake ci

# blocklist
branches:
  except:
  - gh-pages
