language: ruby

sudo: false

notifications:
  email: false

rvm:
  - 2.4.0

env:
  - "RAILS_ENV=test"

bundler_args: --without production deployment

before_script:
  - bin/rails db:test:prepare

# blocklist
branches:
  except:
  - gh-pages
